// Generated by gencpp from file dfcv_mining_msgs/BehaviorEx.msg
// DO NOT EDIT!


#ifndef DFCV_MINING_MSGS_MESSAGE_BEHAVIOREX_H
#define DFCV_MINING_MSGS_MESSAGE_BEHAVIOREX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dfcv_mining_msgs
{
template <class ContainerAllocator>
struct BehaviorEx_
{
  typedef BehaviorEx_<ContainerAllocator> Type;

  BehaviorEx_()
    : header()
    , BehaviorCoordinate_NumberBehaviorID(0)
    , BehaviorCoordinate_GearRequest(0)
    , BehaviorCoordinate_CreepMode(0)
    , BehaviorCoordinate_Slope(0.0)
    , BehaviorCoordinate_parkflag(0)  {
    }
  BehaviorEx_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , BehaviorCoordinate_NumberBehaviorID(0)
    , BehaviorCoordinate_GearRequest(0)
    , BehaviorCoordinate_CreepMode(0)
    , BehaviorCoordinate_Slope(0.0)
    , BehaviorCoordinate_parkflag(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _BehaviorCoordinate_NumberBehaviorID_type;
  _BehaviorCoordinate_NumberBehaviorID_type BehaviorCoordinate_NumberBehaviorID;

   typedef uint8_t _BehaviorCoordinate_GearRequest_type;
  _BehaviorCoordinate_GearRequest_type BehaviorCoordinate_GearRequest;

   typedef uint8_t _BehaviorCoordinate_CreepMode_type;
  _BehaviorCoordinate_CreepMode_type BehaviorCoordinate_CreepMode;

   typedef double _BehaviorCoordinate_Slope_type;
  _BehaviorCoordinate_Slope_type BehaviorCoordinate_Slope;

   typedef uint8_t _BehaviorCoordinate_parkflag_type;
  _BehaviorCoordinate_parkflag_type BehaviorCoordinate_parkflag;





  typedef boost::shared_ptr< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorEx_

typedef ::dfcv_mining_msgs::BehaviorEx_<std::allocator<void> > BehaviorEx;

typedef boost::shared_ptr< ::dfcv_mining_msgs::BehaviorEx > BehaviorExPtr;
typedef boost::shared_ptr< ::dfcv_mining_msgs::BehaviorEx const> BehaviorExConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator1> & lhs, const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.BehaviorCoordinate_NumberBehaviorID == rhs.BehaviorCoordinate_NumberBehaviorID &&
    lhs.BehaviorCoordinate_GearRequest == rhs.BehaviorCoordinate_GearRequest &&
    lhs.BehaviorCoordinate_CreepMode == rhs.BehaviorCoordinate_CreepMode &&
    lhs.BehaviorCoordinate_Slope == rhs.BehaviorCoordinate_Slope &&
    lhs.BehaviorCoordinate_parkflag == rhs.BehaviorCoordinate_parkflag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator1> & lhs, const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dfcv_mining_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d86ef952bcbb397562e23f006336d4a4";
  }

  static const char* value(const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd86ef952bcbb3975ULL;
  static const uint64_t static_value2 = 0x62e23f006336d4a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfcv_mining_msgs/BehaviorEx";
  }

  static const char* value(const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 BehaviorCoordinate_NumberBehaviorID    \n"
"uint8 BehaviorCoordinate_GearRequest\n"
"uint8 BehaviorCoordinate_CreepMode\n"
"float64 BehaviorCoordinate_Slope\n"
"uint8 BehaviorCoordinate_parkflag\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.BehaviorCoordinate_NumberBehaviorID);
      stream.next(m.BehaviorCoordinate_GearRequest);
      stream.next(m.BehaviorCoordinate_CreepMode);
      stream.next(m.BehaviorCoordinate_Slope);
      stream.next(m.BehaviorCoordinate_parkflag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorEx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dfcv_mining_msgs::BehaviorEx_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "BehaviorCoordinate_NumberBehaviorID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BehaviorCoordinate_NumberBehaviorID);
    s << indent << "BehaviorCoordinate_GearRequest: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BehaviorCoordinate_GearRequest);
    s << indent << "BehaviorCoordinate_CreepMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BehaviorCoordinate_CreepMode);
    s << indent << "BehaviorCoordinate_Slope: ";
    Printer<double>::stream(s, indent + "  ", v.BehaviorCoordinate_Slope);
    s << indent << "BehaviorCoordinate_parkflag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.BehaviorCoordinate_parkflag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DFCV_MINING_MSGS_MESSAGE_BEHAVIOREX_H
