// Generated by gencpp from file dfcv_mining_msgs/CTRL_TO_CAN.msg
// DO NOT EDIT!


#ifndef DFCV_MINING_MSGS_MESSAGE_CTRL_TO_CAN_H
#define DFCV_MINING_MSGS_MESSAGE_CTRL_TO_CAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dfcv_mining_msgs
{
template <class ContainerAllocator>
struct CTRL_TO_CAN_
{
  typedef CTRL_TO_CAN_<ContainerAllocator> Type;

  CTRL_TO_CAN_()
    : DRMC_CrpCmp_flg(0)
    , Lift_LiftCmp_flq(0)  {
    }
  CTRL_TO_CAN_(const ContainerAllocator& _alloc)
    : DRMC_CrpCmp_flg(0)
    , Lift_LiftCmp_flq(0)  {
  (void)_alloc;
    }



   typedef uint8_t _DRMC_CrpCmp_flg_type;
  _DRMC_CrpCmp_flg_type DRMC_CrpCmp_flg;

   typedef uint8_t _Lift_LiftCmp_flq_type;
  _Lift_LiftCmp_flq_type Lift_LiftCmp_flq;





  typedef boost::shared_ptr< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> const> ConstPtr;

}; // struct CTRL_TO_CAN_

typedef ::dfcv_mining_msgs::CTRL_TO_CAN_<std::allocator<void> > CTRL_TO_CAN;

typedef boost::shared_ptr< ::dfcv_mining_msgs::CTRL_TO_CAN > CTRL_TO_CANPtr;
typedef boost::shared_ptr< ::dfcv_mining_msgs::CTRL_TO_CAN const> CTRL_TO_CANConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dfcv_mining_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dfcv_mining_msgs': ['/home/yz/catkin_ws/src/dfcv_mining_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3c99c82503600448f81117e4463f647";
  }

  static const char* value(const ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3c99c8250360044ULL;
  static const uint64_t static_value2 = 0x8f81117e4463f647ULL;
};

template<class ContainerAllocator>
struct DataType< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfcv_mining_msgs/CTRL_TO_CAN";
  }

  static const char* value(const ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 DRMC_CrpCmp_flg\n\
uint8 Lift_LiftCmp_flq\n\
";
  }

  static const char* value(const ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DRMC_CrpCmp_flg);
      stream.next(m.Lift_LiftCmp_flq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CTRL_TO_CAN_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dfcv_mining_msgs::CTRL_TO_CAN_<ContainerAllocator>& v)
  {
    s << indent << "DRMC_CrpCmp_flg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.DRMC_CrpCmp_flg);
    s << indent << "Lift_LiftCmp_flq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Lift_LiftCmp_flq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DFCV_MINING_MSGS_MESSAGE_CTRL_TO_CAN_H
