// Generated by gencpp from file dfcv_mining_msgs/EPBC1_ADU.msg
// DO NOT EDIT!


#ifndef DFCV_MINING_MSGS_MESSAGE_EPBC1_ADU_H
#define DFCV_MINING_MSGS_MESSAGE_EPBC1_ADU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dfcv_mining_msgs
{
template <class ContainerAllocator>
struct EPBC1_ADU_
{
  typedef EPBC1_ADU_<ContainerAllocator> Type;

  EPBC1_ADU_()
    : ExternalBrakeControl(0)
    , TractorBrakeControl(0)
    , TrailerBrakeControl(0)
    , ParkingBrakeControl(0)
    , AutoholdBrakeControl(0)
    , WorkingMode(0)
    , CSUM(0)  {
    }
  EPBC1_ADU_(const ContainerAllocator& _alloc)
    : ExternalBrakeControl(0)
    , TractorBrakeControl(0)
    , TrailerBrakeControl(0)
    , ParkingBrakeControl(0)
    , AutoholdBrakeControl(0)
    , WorkingMode(0)
    , CSUM(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ExternalBrakeControl_type;
  _ExternalBrakeControl_type ExternalBrakeControl;

   typedef uint8_t _TractorBrakeControl_type;
  _TractorBrakeControl_type TractorBrakeControl;

   typedef uint8_t _TrailerBrakeControl_type;
  _TrailerBrakeControl_type TrailerBrakeControl;

   typedef uint8_t _ParkingBrakeControl_type;
  _ParkingBrakeControl_type ParkingBrakeControl;

   typedef uint8_t _AutoholdBrakeControl_type;
  _AutoholdBrakeControl_type AutoholdBrakeControl;

   typedef uint8_t _WorkingMode_type;
  _WorkingMode_type WorkingMode;

   typedef uint8_t _CSUM_type;
  _CSUM_type CSUM;





  typedef boost::shared_ptr< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> const> ConstPtr;

}; // struct EPBC1_ADU_

typedef ::dfcv_mining_msgs::EPBC1_ADU_<std::allocator<void> > EPBC1_ADU;

typedef boost::shared_ptr< ::dfcv_mining_msgs::EPBC1_ADU > EPBC1_ADUPtr;
typedef boost::shared_ptr< ::dfcv_mining_msgs::EPBC1_ADU const> EPBC1_ADUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dfcv_mining_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dfcv_mining_msgs': ['/home/yz/catkin_ws/src/dfcv_mining_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc47063186387390f2ee210bfb5d1266";
  }

  static const char* value(const ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc47063186387390ULL;
  static const uint64_t static_value2 = 0xf2ee210bfb5d1266ULL;
};

template<class ContainerAllocator>
struct DataType< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfcv_mining_msgs/EPBC1_ADU";
  }

  static const char* value(const ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#EPBC1_ADU.msg\n\
\n\
uint8 ExternalBrakeControl\n\
uint8 TractorBrakeControl\n\
uint8 TrailerBrakeControl\n\
uint8 ParkingBrakeControl\n\
uint8 AutoholdBrakeControl\n\
uint8 WorkingMode\n\
uint8 CSUM\n\
";
  }

  static const char* value(const ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ExternalBrakeControl);
      stream.next(m.TractorBrakeControl);
      stream.next(m.TrailerBrakeControl);
      stream.next(m.ParkingBrakeControl);
      stream.next(m.AutoholdBrakeControl);
      stream.next(m.WorkingMode);
      stream.next(m.CSUM);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EPBC1_ADU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dfcv_mining_msgs::EPBC1_ADU_<ContainerAllocator>& v)
  {
    s << indent << "ExternalBrakeControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ExternalBrakeControl);
    s << indent << "TractorBrakeControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TractorBrakeControl);
    s << indent << "TrailerBrakeControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TrailerBrakeControl);
    s << indent << "ParkingBrakeControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ParkingBrakeControl);
    s << indent << "AutoholdBrakeControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.AutoholdBrakeControl);
    s << indent << "WorkingMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.WorkingMode);
    s << indent << "CSUM: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.CSUM);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DFCV_MINING_MSGS_MESSAGE_EPBC1_ADU_H
