// Generated by gencpp from file dfcv_mining_msgs/LocationEx.msg
// DO NOT EDIT!


#ifndef DFCV_MINING_MSGS_MESSAGE_LOCATIONEX_H
#define DFCV_MINING_MSGS_MESSAGE_LOCATIONEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dfcv_mining_msgs
{
template <class ContainerAllocator>
struct LocationEx_
{
  typedef LocationEx_<ContainerAllocator> Type;

  LocationEx_()
    : header()
    , LocationEx_X(0.0)
    , LocationEx_Y(0.0)
    , LocationEx_Z(0.0)
    , LocationEx_yaw(0.0)
    , LocationEx_roll(0.0)
    , LocationEx_pitch(0.0)  {
    }
  LocationEx_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , LocationEx_X(0.0)
    , LocationEx_Y(0.0)
    , LocationEx_Z(0.0)
    , LocationEx_yaw(0.0)
    , LocationEx_roll(0.0)
    , LocationEx_pitch(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _LocationEx_X_type;
  _LocationEx_X_type LocationEx_X;

   typedef double _LocationEx_Y_type;
  _LocationEx_Y_type LocationEx_Y;

   typedef double _LocationEx_Z_type;
  _LocationEx_Z_type LocationEx_Z;

   typedef double _LocationEx_yaw_type;
  _LocationEx_yaw_type LocationEx_yaw;

   typedef double _LocationEx_roll_type;
  _LocationEx_roll_type LocationEx_roll;

   typedef double _LocationEx_pitch_type;
  _LocationEx_pitch_type LocationEx_pitch;





  typedef boost::shared_ptr< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> const> ConstPtr;

}; // struct LocationEx_

typedef ::dfcv_mining_msgs::LocationEx_<std::allocator<void> > LocationEx;

typedef boost::shared_ptr< ::dfcv_mining_msgs::LocationEx > LocationExPtr;
typedef boost::shared_ptr< ::dfcv_mining_msgs::LocationEx const> LocationExConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dfcv_mining_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'dfcv_mining_msgs': ['/home/yz/catkin_ws/src/dfcv_mining_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6005d16668b0c658a4987a5ab3ea25b4";
  }

  static const char* value(const ::dfcv_mining_msgs::LocationEx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6005d16668b0c658ULL;
  static const uint64_t static_value2 = 0xa4987a5ab3ea25b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfcv_mining_msgs/LocationEx";
  }

  static const char* value(const ::dfcv_mining_msgs::LocationEx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 LocationEx_X\n\
float64 LocationEx_Y\n\
float64 LocationEx_Z\n\
\n\
float64 LocationEx_yaw\n\
float64 LocationEx_roll\n\
float64 LocationEx_pitch\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dfcv_mining_msgs::LocationEx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.LocationEx_X);
      stream.next(m.LocationEx_Y);
      stream.next(m.LocationEx_Z);
      stream.next(m.LocationEx_yaw);
      stream.next(m.LocationEx_roll);
      stream.next(m.LocationEx_pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocationEx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfcv_mining_msgs::LocationEx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dfcv_mining_msgs::LocationEx_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "LocationEx_X: ";
    Printer<double>::stream(s, indent + "  ", v.LocationEx_X);
    s << indent << "LocationEx_Y: ";
    Printer<double>::stream(s, indent + "  ", v.LocationEx_Y);
    s << indent << "LocationEx_Z: ";
    Printer<double>::stream(s, indent + "  ", v.LocationEx_Z);
    s << indent << "LocationEx_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.LocationEx_yaw);
    s << indent << "LocationEx_roll: ";
    Printer<double>::stream(s, indent + "  ", v.LocationEx_roll);
    s << indent << "LocationEx_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.LocationEx_pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DFCV_MINING_MSGS_MESSAGE_LOCATIONEX_H
