// Generated by gencpp from file dfcv_mining_msgs/PTODE.msg
// DO NOT EDIT!


#ifndef DFCV_MINING_MSGS_MESSAGE_PTODE_H
#define DFCV_MINING_MSGS_MESSAGE_PTODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dfcv_mining_msgs
{
template <class ContainerAllocator>
struct PTODE_
{
  typedef PTODE_<ContainerAllocator> Type;

  PTODE_()
    : EnableSwitch_TransmissionInputShaftPTO_1(0)
    , EnableSwitch_TransmissionInputShaftPTO_2(0)  {
    }
  PTODE_(const ContainerAllocator& _alloc)
    : EnableSwitch_TransmissionInputShaftPTO_1(0)
    , EnableSwitch_TransmissionInputShaftPTO_2(0)  {
  (void)_alloc;
    }



   typedef uint8_t _EnableSwitch_TransmissionInputShaftPTO_1_type;
  _EnableSwitch_TransmissionInputShaftPTO_1_type EnableSwitch_TransmissionInputShaftPTO_1;

   typedef uint8_t _EnableSwitch_TransmissionInputShaftPTO_2_type;
  _EnableSwitch_TransmissionInputShaftPTO_2_type EnableSwitch_TransmissionInputShaftPTO_2;





  typedef boost::shared_ptr< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> const> ConstPtr;

}; // struct PTODE_

typedef ::dfcv_mining_msgs::PTODE_<std::allocator<void> > PTODE;

typedef boost::shared_ptr< ::dfcv_mining_msgs::PTODE > PTODEPtr;
typedef boost::shared_ptr< ::dfcv_mining_msgs::PTODE const> PTODEConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dfcv_mining_msgs::PTODE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dfcv_mining_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dfcv_mining_msgs': ['/home/yz/catkin_ws/src/dfcv_mining_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bffb4a10fce1c42fd34040f1e034c91a";
  }

  static const char* value(const ::dfcv_mining_msgs::PTODE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbffb4a10fce1c42fULL;
  static const uint64_t static_value2 = 0xd34040f1e034c91aULL;
};

template<class ContainerAllocator>
struct DataType< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfcv_mining_msgs/PTODE";
  }

  static const char* value(const ::dfcv_mining_msgs::PTODE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#PTODE.msg\n\
\n\
uint8 EnableSwitch_TransmissionInputShaftPTO_1\n\
uint8 EnableSwitch_TransmissionInputShaftPTO_2\n\
";
  }

  static const char* value(const ::dfcv_mining_msgs::PTODE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.EnableSwitch_TransmissionInputShaftPTO_1);
      stream.next(m.EnableSwitch_TransmissionInputShaftPTO_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PTODE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfcv_mining_msgs::PTODE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dfcv_mining_msgs::PTODE_<ContainerAllocator>& v)
  {
    s << indent << "EnableSwitch_TransmissionInputShaftPTO_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EnableSwitch_TransmissionInputShaftPTO_1);
    s << indent << "EnableSwitch_TransmissionInputShaftPTO_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.EnableSwitch_TransmissionInputShaftPTO_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DFCV_MINING_MSGS_MESSAGE_PTODE_H
