// Generated by gencpp from file canbus/Ros2canbus.msg
// DO NOT EDIT!


#ifndef CANBUS_MESSAGE_ROS2CANBUS_H
#define CANBUS_MESSAGE_ROS2CANBUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace canbus
{
template <class ContainerAllocator>
struct Ros2canbus_
{
  typedef Ros2canbus_<ContainerAllocator> Type;

  Ros2canbus_()
    : time_pub(0)
    , time_meas(0)
    , channel_id(0)
    , can_id(0)
    , data()  {
      data.assign(0);
  }
  Ros2canbus_(const ContainerAllocator& _alloc)
    : time_pub(0)
    , time_meas(0)
    , channel_id(0)
    , can_id(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef int64_t _time_pub_type;
  _time_pub_type time_pub;

   typedef int64_t _time_meas_type;
  _time_meas_type time_meas;

   typedef int8_t _channel_id_type;
  _channel_id_type channel_id;

   typedef int32_t _can_id_type;
  _can_id_type can_id;

   typedef boost::array<int8_t, 8>  _data_type;
  _data_type data;


  typedef boost::shared_ptr< ::canbus::Ros2canbus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canbus::Ros2canbus_<ContainerAllocator> const> ConstPtr;

}; // struct Ros2canbus_

typedef ::canbus::Ros2canbus_<std::allocator<void> > Ros2canbus;

typedef boost::shared_ptr< ::canbus::Ros2canbus > Ros2canbusPtr;
typedef boost::shared_ptr< ::canbus::Ros2canbus const> Ros2canbusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canbus::Ros2canbus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canbus::Ros2canbus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::canbus::Ros2canbus_<ContainerAllocator1> & lhs, const ::canbus::Ros2canbus_<ContainerAllocator2> & rhs)
{
  return lhs.time_pub == rhs.time_pub &&
    lhs.time_meas == rhs.time_meas &&
    lhs.channel_id == rhs.channel_id &&
    lhs.can_id == rhs.can_id &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::canbus::Ros2canbus_<ContainerAllocator1> & lhs, const ::canbus::Ros2canbus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace canbus

namespace ros
{
namespace message_traits
{



template <class ContainerAllocator>
struct IsFixedSize< ::canbus::Ros2canbus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus::Ros2canbus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus::Ros2canbus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus::Ros2canbus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus::Ros2canbus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus::Ros2canbus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canbus::Ros2canbus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "266c4a1f2195e97edfd0ab815ac12b76";
  }

  static const char* value(const ::canbus::Ros2canbus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x266c4a1f2195e97eULL;
  static const uint64_t static_value2 = 0xdfd0ab815ac12b76ULL;
};

template<class ContainerAllocator>
struct DataType< ::canbus::Ros2canbus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canbus/Ros2canbus";
  }

  static const char* value(const ::canbus::Ros2canbus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canbus::Ros2canbus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 time_pub\n"
"int64 time_meas\n"
"int8 channel_id\n"
"int32 can_id\n"
"int8[8] data\n"
;
  }

  static const char* value(const ::canbus::Ros2canbus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canbus::Ros2canbus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_pub);
      stream.next(m.time_meas);
      stream.next(m.channel_id);
      stream.next(m.can_id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ros2canbus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canbus::Ros2canbus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canbus::Ros2canbus_<ContainerAllocator>& v)
  {
    s << indent << "time_pub: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time_pub);
    s << indent << "time_meas: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time_meas);
    s << indent << "channel_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.channel_id);
    s << indent << "can_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.can_id);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANBUS_MESSAGE_ROS2CANBUS_H
