// Generated by gencpp from file dfcv_mining_msgs/Sys_stADMd_mp.msg
// DO NOT EDIT!


#ifndef DFCV_MINING_MSGS_MESSAGE_SYS_STADMD_MP_H
#define DFCV_MINING_MSGS_MESSAGE_SYS_STADMD_MP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dfcv_mining_msgs
{
template <class ContainerAllocator>
struct Sys_stADMd_mp_
{
  typedef Sys_stADMd_mp_<ContainerAllocator> Type;

  Sys_stADMd_mp_()
    : Sys_stADMd_mp(0)  {
    }
  Sys_stADMd_mp_(const ContainerAllocator& _alloc)
    : Sys_stADMd_mp(0)  {
  (void)_alloc;
    }



   typedef uint8_t _Sys_stADMd_mp_type;
  _Sys_stADMd_mp_type Sys_stADMd_mp;





  typedef boost::shared_ptr< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> const> ConstPtr;

}; // struct Sys_stADMd_mp_

typedef ::dfcv_mining_msgs::Sys_stADMd_mp_<std::allocator<void> > Sys_stADMd_mp;

typedef boost::shared_ptr< ::dfcv_mining_msgs::Sys_stADMd_mp > Sys_stADMd_mpPtr;
typedef boost::shared_ptr< ::dfcv_mining_msgs::Sys_stADMd_mp const> Sys_stADMd_mpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dfcv_mining_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dfcv_mining_msgs': ['/home/yz/catkin_ws/src/dfcv_mining_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9143b74eff1ba37fcae28c895f25b483";
  }

  static const char* value(const ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9143b74eff1ba37fULL;
  static const uint64_t static_value2 = 0xcae28c895f25b483ULL;
};

template<class ContainerAllocator>
struct DataType< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfcv_mining_msgs/Sys_stADMd_mp";
  }

  static const char* value(const ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 Sys_stADMd_mp\n\
";
  }

  static const char* value(const ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Sys_stADMd_mp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sys_stADMd_mp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dfcv_mining_msgs::Sys_stADMd_mp_<ContainerAllocator>& v)
  {
    s << indent << "Sys_stADMd_mp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Sys_stADMd_mp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DFCV_MINING_MSGS_MESSAGE_SYS_STADMD_MP_H
