// Generated by gencpp from file df_msgs/TBOXMOVE.msg
// DO NOT EDIT!


#ifndef DF_MSGS_MESSAGE_TBOXMOVE_H
#define DF_MSGS_MESSAGE_TBOXMOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace df_msgs
{
template <class ContainerAllocator>
struct TBOXMOVE_
{
  typedef TBOXMOVE_<ContainerAllocator> Type;

  TBOXMOVE_()
    : questnum(0)
    , questtype(0)
    , questoperation(0)
    , limitspeed(0)
    , start_X(0)
    , start_Y(0)
    , start_Z(0)
    , end_X(0)
    , end_Y(0)
    , end_Z(0)
    , idlength(0)
    , id()  {
    }
  TBOXMOVE_(const ContainerAllocator& _alloc)
    : questnum(0)
    , questtype(0)
    , questoperation(0)
    , limitspeed(0)
    , start_X(0)
    , start_Y(0)
    , start_Z(0)
    , end_X(0)
    , end_Y(0)
    , end_Z(0)
    , idlength(0)
    , id(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _questnum_type;
  _questnum_type questnum;

   typedef uint8_t _questtype_type;
  _questtype_type questtype;

   typedef uint8_t _questoperation_type;
  _questoperation_type questoperation;

   typedef uint16_t _limitspeed_type;
  _limitspeed_type limitspeed;

   typedef uint64_t _start_X_type;
  _start_X_type start_X;

   typedef uint64_t _start_Y_type;
  _start_Y_type start_Y;

   typedef uint64_t _start_Z_type;
  _start_Z_type start_Z;

   typedef uint64_t _end_X_type;
  _end_X_type end_X;

   typedef uint64_t _end_Y_type;
  _end_Y_type end_Y;

   typedef uint64_t _end_Z_type;
  _end_Z_type end_Z;

   typedef uint8_t _idlength_type;
  _idlength_type idlength;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::df_msgs::TBOXMOVE_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::df_msgs::TBOXMOVE_<ContainerAllocator> const> ConstPtr;

}; // struct TBOXMOVE_

typedef ::df_msgs::TBOXMOVE_<std::allocator<void> > TBOXMOVE;

typedef boost::shared_ptr< ::df_msgs::TBOXMOVE > TBOXMOVEPtr;
typedef boost::shared_ptr< ::df_msgs::TBOXMOVE const> TBOXMOVEConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::df_msgs::TBOXMOVE_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::df_msgs::TBOXMOVE_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace df_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'df_msgs': ['/home/yangchun/catkin_ws/catkin_ws/src/ROS-Academy-for-Beginners/df_msgs/msg', '/home/yangchun/catkin_ws/catkin_ws/devel/share/df_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::df_msgs::TBOXMOVE_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::df_msgs::TBOXMOVE_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::df_msgs::TBOXMOVE_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4370d2de8613dcc7f3790e68438216e9";
  }

  static const char* value(const ::df_msgs::TBOXMOVE_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4370d2de8613dcc7ULL;
  static const uint64_t static_value2 = 0xf3790e68438216e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df_msgs/TBOXMOVE";
  }

  static const char* value(const ::df_msgs::TBOXMOVE_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#TBOXMOVE.msg\n\
\n\
uint64 questnum\n\
uint8 questtype\n\
uint8 questoperation\n\
uint16 limitspeed\n\
uint64 start_X\n\
uint64 start_Y\n\
uint64 start_Z\n\
uint64 end_X\n\
uint64 end_Y\n\
uint64 end_Z\n\
uint8 idlength\n\
uint32[] id\n\
\n\
";
  }

  static const char* value(const ::df_msgs::TBOXMOVE_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.questnum);
      stream.next(m.questtype);
      stream.next(m.questoperation);
      stream.next(m.limitspeed);
      stream.next(m.start_X);
      stream.next(m.start_Y);
      stream.next(m.start_Z);
      stream.next(m.end_X);
      stream.next(m.end_Y);
      stream.next(m.end_Z);
      stream.next(m.idlength);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TBOXMOVE_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::df_msgs::TBOXMOVE_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::df_msgs::TBOXMOVE_<ContainerAllocator>& v)
  {
    s << indent << "questnum: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.questnum);
    s << indent << "questtype: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.questtype);
    s << indent << "questoperation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.questoperation);
    s << indent << "limitspeed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.limitspeed);
    s << indent << "start_X: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.start_X);
    s << indent << "start_Y: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.start_Y);
    s << indent << "start_Z: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.start_Z);
    s << indent << "end_X: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.end_X);
    s << indent << "end_Y: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.end_Y);
    s << indent << "end_Z: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.end_Z);
    s << indent << "idlength: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.idlength);
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DF_MSGS_MESSAGE_TBOXMOVE_H
