/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Thu Jun  1 16:20:57 2023.
 */

#include <string.h>

#include "../include/ins570d.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int ins570d_gps_triaxial_attitude_pack(
    uint8_t *dst_p,
    const struct ins570d_gps_triaxial_attitude_t *src_p,
    size_t size)
{
    uint16_t gps_rev;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->gps_course, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->gps_course, 8u, 0xffu);
    gps_rev = (uint16_t)src_p->gps_rev;
    dst_p[2] |= pack_left_shift_u16(gps_rev, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gps_rev, 8u, 0xffu);

    return (4);
}

int ins570d_gps_triaxial_attitude_unpack(
    struct ins570d_gps_triaxial_attitude_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gps_rev;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->gps_course = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->gps_course |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    gps_rev = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gps_rev |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gps_rev = (int16_t)gps_rev;

    return (0);
}

uint16_t ins570d_gps_triaxial_attitude_gps_course_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double ins570d_gps_triaxial_attitude_gps_course_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_gps_triaxial_attitude_gps_course_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_gps_triaxial_attitude_gps_rev_encode(double value)
{
    return (int16_t)(value);
}

double ins570d_gps_triaxial_attitude_gps_rev_decode(int16_t value)
{
    return ((double)value);
}

bool ins570d_gps_triaxial_attitude_gps_rev_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ins570d_gps_alt_flag_pack(
    uint8_t *dst_p,
    const struct ins570d_gps_alt_flag_t *src_p,
    size_t size)
{
    uint32_t gps_alt;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    gps_alt = (uint32_t)src_p->gps_alt;
    dst_p[0] |= pack_left_shift_u32(gps_alt, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gps_alt, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(gps_alt, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(gps_alt, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->gps_flag, 0u, 0xffu);

    return (5);
}

int ins570d_gps_alt_flag_unpack(
    struct ins570d_gps_alt_flag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t gps_alt;

    if (size < 5u) {
        return (-EINVAL);
    }

    gps_alt = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    gps_alt |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gps_alt |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    gps_alt |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->gps_alt = (int32_t)gps_alt;
    dst_p->gps_flag = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int32_t ins570d_gps_alt_flag_gps_alt_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double ins570d_gps_alt_flag_gps_alt_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool ins570d_gps_alt_flag_gps_alt_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

uint8_t ins570d_gps_alt_flag_gps_flag_encode(double value)
{
    return (uint8_t)(value);
}

double ins570d_gps_alt_flag_gps_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool ins570d_gps_alt_flag_gps_flag_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ins570d_gps_threewayspeed_pack(
    uint8_t *dst_p,
    const struct ins570d_gps_threewayspeed_t *src_p,
    size_t size)
{
    uint16_t gps_east_velocity;
    uint16_t gps_north_velocity;
    uint16_t gps_up_velocity;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    gps_east_velocity = (uint16_t)src_p->gps_east_velocity;
    dst_p[0] |= pack_left_shift_u16(gps_east_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(gps_east_velocity, 8u, 0xffu);
    gps_north_velocity = (uint16_t)src_p->gps_north_velocity;
    dst_p[2] |= pack_left_shift_u16(gps_north_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(gps_north_velocity, 8u, 0xffu);
    gps_up_velocity = (uint16_t)src_p->gps_up_velocity;
    dst_p[4] |= pack_left_shift_u16(gps_up_velocity, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(gps_up_velocity, 8u, 0xffu);

    return (6);
}

int ins570d_gps_threewayspeed_unpack(
    struct ins570d_gps_threewayspeed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t gps_east_velocity;
    uint16_t gps_north_velocity;
    uint16_t gps_up_velocity;

    if (size < 6u) {
        return (-EINVAL);
    }

    gps_east_velocity = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    gps_east_velocity |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gps_east_velocity = (int16_t)gps_east_velocity;
    gps_north_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    gps_north_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->gps_north_velocity = (int16_t)gps_north_velocity;
    gps_up_velocity = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    gps_up_velocity |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->gps_up_velocity = (int16_t)gps_up_velocity;

    return (0);
}

int16_t ins570d_gps_threewayspeed_gps_east_velocity_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_gps_threewayspeed_gps_east_velocity_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_gps_threewayspeed_gps_east_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_gps_threewayspeed_gps_north_velocity_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_gps_threewayspeed_gps_north_velocity_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_gps_threewayspeed_gps_north_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_gps_threewayspeed_gps_up_velocity_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_gps_threewayspeed_gps_up_velocity_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_gps_threewayspeed_gps_up_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ins570d_gps_lat_lon_pack(
    uint8_t *dst_p,
    const struct ins570d_gps_lat_lon_t *src_p,
    size_t size)
{
    uint32_t gps_lat;
    uint32_t gps_lon;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    gps_lat = (uint32_t)src_p->gps_lat;
    dst_p[0] |= pack_left_shift_u32(gps_lat, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(gps_lat, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(gps_lat, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(gps_lat, 24u, 0xffu);
    gps_lon = (uint32_t)src_p->gps_lon;
    dst_p[4] |= pack_left_shift_u32(gps_lon, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(gps_lon, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(gps_lon, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(gps_lon, 24u, 0xffu);

    return (8);
}

int ins570d_gps_lat_lon_unpack(
    struct ins570d_gps_lat_lon_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t gps_lat;
    uint32_t gps_lon;

    if (size < 8u) {
        return (-EINVAL);
    }

    gps_lat = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    gps_lat |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    gps_lat |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    gps_lat |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->gps_lat = (int32_t)gps_lat;
    gps_lon = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    gps_lon |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    gps_lon |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    gps_lon |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->gps_lon = (int32_t)gps_lon;

    return (0);
}

int32_t ins570d_gps_lat_lon_gps_lat_encode(double value)
{
    return (int32_t)(value / 1E-7);
}

double ins570d_gps_lat_lon_gps_lat_decode(int32_t value)
{
    return ((double)value * 1E-7);
}

bool ins570d_gps_lat_lon_gps_lat_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t ins570d_gps_lat_lon_gps_lon_encode(double value)
{
    return (int32_t)(value / 1E-7);
}

double ins570d_gps_lat_lon_gps_lon_decode(int32_t value)
{
    return ((double)value * 1E-7);
}

bool ins570d_gps_lat_lon_gps_lon_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int ins570d_gps_time_pack(
    uint8_t *dst_p,
    const struct ins570d_gps_time_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->gps_week, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->gps_week, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->gps_millisecond, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->gps_millisecond, 8u, 0xffu);

    return (6);
}

int ins570d_gps_time_unpack(
    struct ins570d_gps_time_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->gps_week = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->gps_week |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->gps_millisecond = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->gps_millisecond |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t ins570d_gps_time_gps_week_encode(double value)
{
    return (uint16_t)(value);
}

double ins570d_gps_time_gps_week_decode(uint16_t value)
{
    return ((double)value);
}

bool ins570d_gps_time_gps_week_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ins570d_gps_time_gps_millisecond_encode(double value)
{
    return (uint16_t)(value);
}

double ins570d_gps_time_gps_millisecond_decode(uint16_t value)
{
    return ((double)value);
}

bool ins570d_gps_time_gps_millisecond_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ins570d_z_gyro_acce_pack(
    uint8_t *dst_p,
    const struct ins570d_z_gyro_acce_t *src_p,
    size_t size)
{
    uint32_t z_acce;
    uint32_t z_gyro;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    z_gyro = (uint32_t)src_p->z_gyro;
    dst_p[0] |= pack_left_shift_u32(z_gyro, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(z_gyro, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(z_gyro, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(z_gyro, 24u, 0xffu);
    z_acce = (uint32_t)src_p->z_acce;
    dst_p[4] |= pack_left_shift_u32(z_acce, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(z_acce, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(z_acce, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(z_acce, 24u, 0xffu);

    return (8);
}

int ins570d_z_gyro_acce_unpack(
    struct ins570d_z_gyro_acce_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t z_acce;
    uint32_t z_gyro;

    if (size < 8u) {
        return (-EINVAL);
    }

    z_gyro = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    z_gyro |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    z_gyro |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    z_gyro |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->z_gyro = (int32_t)z_gyro;
    z_acce = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    z_acce |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    z_acce |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    z_acce |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->z_acce = (int32_t)z_acce;

    return (0);
}

int32_t ins570d_z_gyro_acce_z_gyro_encode(double value)
{
    return (int32_t)(value / 0.00001);
}

double ins570d_z_gyro_acce_z_gyro_decode(int32_t value)
{
    return ((double)value * 0.00001);
}

bool ins570d_z_gyro_acce_z_gyro_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t ins570d_z_gyro_acce_z_acce_encode(double value)
{
    return (int32_t)(value / 0.00001);
}

double ins570d_z_gyro_acce_z_acce_decode(int32_t value)
{
    return ((double)value * 0.00001);
}

bool ins570d_z_gyro_acce_z_acce_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int ins570d_x_y_gyro_pack(
    uint8_t *dst_p,
    const struct ins570d_x_y_gyro_t *src_p,
    size_t size)
{
    uint32_t x_gyro;
    uint32_t y_gyro;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    x_gyro = (uint32_t)src_p->x_gyro;
    dst_p[0] |= pack_left_shift_u32(x_gyro, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(x_gyro, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(x_gyro, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(x_gyro, 24u, 0xffu);
    y_gyro = (uint32_t)src_p->y_gyro;
    dst_p[4] |= pack_left_shift_u32(y_gyro, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(y_gyro, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(y_gyro, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(y_gyro, 24u, 0xffu);

    return (8);
}

int ins570d_x_y_gyro_unpack(
    struct ins570d_x_y_gyro_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t x_gyro;
    uint32_t y_gyro;

    if (size < 8u) {
        return (-EINVAL);
    }

    x_gyro = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    x_gyro |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    x_gyro |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    x_gyro |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->x_gyro = (int32_t)x_gyro;
    y_gyro = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    y_gyro |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    y_gyro |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    y_gyro |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->y_gyro = (int32_t)y_gyro;

    return (0);
}

int32_t ins570d_x_y_gyro_x_gyro_encode(double value)
{
    return (int32_t)(value / 0.00001);
}

double ins570d_x_y_gyro_x_gyro_decode(int32_t value)
{
    return ((double)value * 0.00001);
}

bool ins570d_x_y_gyro_x_gyro_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t ins570d_x_y_gyro_y_gyro_encode(double value)
{
    return (int32_t)(value / 0.00001);
}

double ins570d_x_y_gyro_y_gyro_decode(int32_t value)
{
    return ((double)value * 0.00001);
}

bool ins570d_x_y_gyro_y_gyro_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int ins570d_x_y_acce_pack(
    uint8_t *dst_p,
    const struct ins570d_x_y_acce_t *src_p,
    size_t size)
{
    uint32_t x_acce;
    uint32_t y_acce;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    x_acce = (uint32_t)src_p->x_acce;
    dst_p[0] |= pack_left_shift_u32(x_acce, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(x_acce, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(x_acce, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(x_acce, 24u, 0xffu);
    y_acce = (uint32_t)src_p->y_acce;
    dst_p[4] |= pack_left_shift_u32(y_acce, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(y_acce, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(y_acce, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(y_acce, 24u, 0xffu);

    return (8);
}

int ins570d_x_y_acce_unpack(
    struct ins570d_x_y_acce_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t x_acce;
    uint32_t y_acce;

    if (size < 8u) {
        return (-EINVAL);
    }

    x_acce = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    x_acce |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    x_acce |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    x_acce |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->x_acce = (int32_t)x_acce;
    y_acce = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    y_acce |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    y_acce |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    y_acce |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->y_acce = (int32_t)y_acce;

    return (0);
}

int32_t ins570d_x_y_acce_x_acce_encode(double value)
{
    return (int32_t)(value / 0.00001);
}

double ins570d_x_y_acce_x_acce_decode(int32_t value)
{
    return ((double)value * 0.00001);
}

bool ins570d_x_y_acce_x_acce_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t ins570d_x_y_acce_y_acce_encode(double value)
{
    return (int32_t)(value / 0.00001);
}

double ins570d_x_y_acce_y_acce_decode(int32_t value)
{
    return ((double)value * 0.00001);
}

bool ins570d_x_y_acce_y_acce_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int ins570d_three_way_speed_pack(
    uint8_t *dst_p,
    const struct ins570d_three_way_speed_t *src_p,
    size_t size)
{
    uint16_t east_velocity;
    uint16_t north_velocity;
    uint16_t up_velocity;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    east_velocity = (uint16_t)src_p->east_velocity;
    dst_p[0] |= pack_left_shift_u16(east_velocity, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(east_velocity, 8u, 0xffu);
    north_velocity = (uint16_t)src_p->north_velocity;
    dst_p[2] |= pack_left_shift_u16(north_velocity, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(north_velocity, 8u, 0xffu);
    up_velocity = (uint16_t)src_p->up_velocity;
    dst_p[4] |= pack_left_shift_u16(up_velocity, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(up_velocity, 8u, 0xffu);

    return (6);
}

int ins570d_three_way_speed_unpack(
    struct ins570d_three_way_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t east_velocity;
    uint16_t north_velocity;
    uint16_t up_velocity;

    if (size < 6u) {
        return (-EINVAL);
    }

    east_velocity = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    east_velocity |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->east_velocity = (int16_t)east_velocity;
    north_velocity = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    north_velocity |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->north_velocity = (int16_t)north_velocity;
    up_velocity = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    up_velocity |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->up_velocity = (int16_t)up_velocity;

    return (0);
}

int16_t ins570d_three_way_speed_east_velocity_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_three_way_speed_east_velocity_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_three_way_speed_east_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_three_way_speed_north_velocity_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_three_way_speed_north_velocity_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_three_way_speed_north_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_three_way_speed_up_velocity_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_three_way_speed_up_velocity_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_three_way_speed_up_velocity_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ins570d_alt_flag_pack(
    uint8_t *dst_p,
    const struct ins570d_alt_flag_t *src_p,
    size_t size)
{
    uint32_t altflag_alt;

    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    altflag_alt = (uint32_t)src_p->altflag_alt;
    dst_p[0] |= pack_left_shift_u32(altflag_alt, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(altflag_alt, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(altflag_alt, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(altflag_alt, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->altflag_flag, 0u, 0xffu);

    return (5);
}

int ins570d_alt_flag_unpack(
    struct ins570d_alt_flag_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t altflag_alt;

    if (size < 5u) {
        return (-EINVAL);
    }

    altflag_alt = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    altflag_alt |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    altflag_alt |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    altflag_alt |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->altflag_alt = (int32_t)altflag_alt;
    dst_p->altflag_flag = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int32_t ins570d_alt_flag_altflag_alt_encode(double value)
{
    return (int32_t)(value / 0.001);
}

double ins570d_alt_flag_altflag_alt_decode(int32_t value)
{
    return ((double)value * 0.001);
}

bool ins570d_alt_flag_altflag_alt_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

uint8_t ins570d_alt_flag_altflag_flag_encode(double value)
{
    return (uint8_t)(value);
}

double ins570d_alt_flag_altflag_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool ins570d_alt_flag_altflag_flag_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ins570d_latitude_long_pack(
    uint8_t *dst_p,
    const struct ins570d_latitude_long_t *src_p,
    size_t size)
{
    uint32_t lat_lon_lat;
    uint32_t lat_lon_lon;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    lat_lon_lat = (uint32_t)src_p->lat_lon_lat;
    dst_p[0] |= pack_left_shift_u32(lat_lon_lat, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(lat_lon_lat, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(lat_lon_lat, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(lat_lon_lat, 24u, 0xffu);
    lat_lon_lon = (uint32_t)src_p->lat_lon_lon;
    dst_p[4] |= pack_left_shift_u32(lat_lon_lon, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(lat_lon_lon, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(lat_lon_lon, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(lat_lon_lon, 24u, 0xffu);

    return (8);
}

int ins570d_latitude_long_unpack(
    struct ins570d_latitude_long_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t lat_lon_lat;
    uint32_t lat_lon_lon;

    if (size < 8u) {
        return (-EINVAL);
    }

    lat_lon_lat = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    lat_lon_lat |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    lat_lon_lat |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    lat_lon_lat |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->lat_lon_lat = (int32_t)lat_lon_lat;
    lat_lon_lon = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    lat_lon_lon |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    lat_lon_lon |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    lat_lon_lon |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->lat_lon_lon = (int32_t)lat_lon_lon;

    return (0);
}

int32_t ins570d_latitude_long_lat_lon_lat_encode(double value)
{
    return (int32_t)(value / 1E-7);
}

double ins570d_latitude_long_lat_lon_lat_decode(int32_t value)
{
    return ((double)value * 1E-7);
}

bool ins570d_latitude_long_lat_lon_lat_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int32_t ins570d_latitude_long_lat_lon_lon_encode(double value)
{
    return (int32_t)(value / 1E-7);
}

double ins570d_latitude_long_lat_lon_lon_decode(int32_t value)
{
    return ((double)value * 1E-7);
}

bool ins570d_latitude_long_lat_lon_lon_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int ins570d_triaxial_attitude_pack(
    uint8_t *dst_p,
    const struct ins570d_triaxial_attitude_t *src_p,
    size_t size)
{
    uint16_t tra_pitch;
    uint16_t tra_roll;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->tra_course, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->tra_course, 8u, 0xffu);
    tra_pitch = (uint16_t)src_p->tra_pitch;
    dst_p[2] |= pack_left_shift_u16(tra_pitch, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(tra_pitch, 8u, 0xffu);
    tra_roll = (uint16_t)src_p->tra_roll;
    dst_p[4] |= pack_left_shift_u16(tra_roll, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(tra_roll, 8u, 0xffu);

    return (6);
}

int ins570d_triaxial_attitude_unpack(
    struct ins570d_triaxial_attitude_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t tra_pitch;
    uint16_t tra_roll;

    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->tra_course = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->tra_course |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    tra_pitch = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    tra_pitch |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->tra_pitch = (int16_t)tra_pitch;
    tra_roll = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    tra_roll |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->tra_roll = (int16_t)tra_roll;

    return (0);
}

uint16_t ins570d_triaxial_attitude_tra_course_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double ins570d_triaxial_attitude_tra_course_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_triaxial_attitude_tra_course_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_triaxial_attitude_tra_pitch_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_triaxial_attitude_tra_pitch_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_triaxial_attitude_tra_pitch_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ins570d_triaxial_attitude_tra_roll_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ins570d_triaxial_attitude_tra_roll_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ins570d_triaxial_attitude_tra_roll_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
